### PR TITLE
fix template index

### PR DESCRIPTION
**Pull request by lemingos**
Looks like [generator](https://github.com/kreteshq/kretes/blob/master/source/cli/generate/component.ts#L25) is writing to `index.tsx` (not `.ts`). I guess the template files should be changed as in PR.

### CODE REVIEW

**Comment by zaiste** [comment]
@lemingos thanks for the suggestion, but `.ts` is OK in this context. Is there something not working on your side?

**Comment by lemingos** [comment]
It doesn't pick up changes in `index.tsx` while `index.ts` is in the project.

**Comment by zaiste** [comment]
@lemingos which `index.tsx` are you referring to? `index.ts` are used only for convenience and those files should contain just the `export` statements, nothing more.

**Comment by lemingos** [comment]
if in `components/index.ts` I do have just:

```
export {App} from './App';
```

It's raising an error in dev tools:

```
Uncaught SyntaxError: The requested module './index.js' does not provide an export named 'Hero'
```

If I remove `components/index.ts` it works.

**Pull request closed without merging**
